### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/street2sat_website#1]
@mangomadhava Do you think it'd be useful to add a README?

**Potential ideas for README**
- Setting up environment
- What the model does
- How the model does it
- Why the predictions are useful
- Associated paper?

**Comment by mangomadhava** [comment]
Added set up information to get the website running locally. Some changes to requirements.txt might still be needed.

**Comment by ivanzvonkov** [comment]
Thanks for the initial push.
Some notes on the README.md.
- Requirements.txt looks good, only got torch install to work when I removed `+cpu`
> 5. Run the app using flask run
- I had to set a variable here
  ```bash
  export FLASK_APP=run
  flask run
  ```

- Do you think the other points from my initial comment above would be redundant / not useful?
> - What the model does
> - How the model does it
> - Why the predictions are useful
> - Associated paper?

**Comment by ivanzvonkov** [comment]
@mangomadhava Did you see my comment here?

**Comment by mangomadhava** [comment]
Yup! Added some information. We can add some example images later. https://github.com/nasaharvest/street2sat_website/blob/main/README.md
