### ISSUE TITLE
Notebook to demonstrate model prediction

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/street2sat_website#2]
I think it might be worthwhile to make a short notebook that imports the model/models and runs them on an example file.
We can then use the same example file to verify model functionality when:
1. Creating the docker image
2. Implementing Google Cloud Bucket connection

@mangomadhava Any thoughts?

**Comment by ivanzvonkov** [comment]
After discussion, I think it would be great for the notebook to do something like this (all psuedo code)

```python
import load_img
import yolo_preddiction
import distance_calculation

expected_yolo_pred = json.loads(...)
expected_distance_pred = json.loads(...)

img = load_img(...)

yolo_pred  = yolo_preddiction(img)
assert yolo_pred = expected_yolo_pred

distance_pred = distance_calculation(img, yolo_pred)
assert expected_distance_pred == distance_pred 

```

Let me know if I am correctly understanding / if above makes sense?
@mangomadhava

**Comment by mangomadhava** [comment]
Added them! Let me know if you anything needs clarification. https://github.com/nasaharvest/street2sat_website/tree/main/noteboooks

Do you want the expected distance calculations to be in a different json file? @ivanzvonkov

**Comment by ivanzvonkov** [comment]
Thanks!
- Please add .ipynb_checkpoints to .gitignore
- I don't think using spaces and commas in filenames is super safe, maybe replace with `_` 

Notebook content is great! Just one comment for **Single image detection and distance prediction .ipynb**
- For `tags = exifread.process_file(img1_file)` consider only printing relevant tags or just showing the thumbnail, right now it's a huge wall of text where only some information is relevant.

> Do you want the expected distance calculations to be in a different json file?

You can leave it as is for now.

**Comment by ivanzvonkov** [comment]
@mangomadhava Did you see my comment here?

**Comment by mangomadhava** [comment]
Removed the print and added lines to gitignore
