### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/street2sat_website#28]
**Context**: This project code has no enforced lining, type checking, or automated unit tests.

**Issue**: Not doing these checks can result in unintended bugs in the project.

**Solution**: Github action for automatically running black, flake8, mypy, isort, unit tests on every PR and merge to main.
Similar to https://github.com/nasaharvest/crop-mask/blob/master/.github/workflows/test.yml

**Comment by ivanzvonkov** [comment]
@adebowaledaniel would you be interested in tackling this one?

**Comment by adebowaledaniel** [comment]
Thanks, @ivanzvonkov; I am interested.
