### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by green512** [nasaharvest/street2sat_website#29]
If the images should be processed to straighten by ourself?
I can't find the  related code in the [Multiple_image_pipeline.ipynb](https://github.com/nasaharvest/street2sat/blob/main/noteboooks/Multiple_image_pipeline.ipynb)

**Comment by mangomadhava** [comment]
Sorry for the delay. Yep, that was included initially but we are not straightening the images anymore. If you are having issues or have questions feel free to email me at madhavapaliyam@gmail.com.
