### ISSUE TITLE
Decouple flask from model code

### ISSUE THREAD

**Issue by ivanzvonkov** [nasaharvest/street2sat_website#3]
A prerequisite to putting the model into TorchServe and Google Cloud is decouping the model code from the flask code.
Flask, torchserve+gcp, even notebooks are all different ways of exposing the model thus I think the following directory structure would make sense:
```
/model
/flask_app
/gcp
/notebooks
```
Then the code inside `flask_app/`, `gcp/`, `notebooks/` can do things like
```python
from model import exif_utils, get_model, run_prediction, get_distance_meters, get_new_points, plot_labels
```
This will ensure that `flask_app/`, `gcp/`, `notebooks/` are not dependent on each other in any way, and will make it much more straightforward to develop on any of the three as the dependency structure is straightforward.

@mangomadhava I think it might make most sense for you to take this on as you know the code the best. Let me know if this is this something you have time to work on?

If yes, feel free to make the change on a separate branch and make a Pull Request so we can discuss!

**Comment by mangomadhava** [comment]
I'll get to this later this week probably Tuesday or Thursday. But overall I think thats a good idea, just need to make sure flask can run properly because sometimes it is a little strange with imports.

**Comment by ivanzvonkov** [comment]
Thanks, it'll make dockerizing a lot easier because flask won't have to be included!

**Comment by mangomadhava** [comment]
Redid the code structure. The flask code should be in the flask_app directory. The street2sat_utils directory contains all the code needed for the street2sat pipeline and can be run without any imports from flask_app. Let me know how it looks.

**Comment by ivanzvonkov** [comment]
Looks great, thank you @mangomadhava!
